### ISSUE TITLE
new Authentication middlewares

### ISSUE THREAD

**Issue by y-golde** [CoronaTeamMOD/CoronaInvestigation#1235]
## Background
This issue is created following user story [1467](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2014?workitem=1467) where its stated that new middlewares are needed to be added.
in the sheet below (which I welcome everybody to look at and edit/comment if I've missed/misunderstood anything) I've mapped all of the different endpoints according to different scopes (that require different authenticating middlewares):
  **INVESTIGATION** - see [HandleInvestigationRequest](https://github.com/CoronaTeamMOD/CoronaInvestigation/blob/dev/server/src/middlewares/HandleInvestigationRequest.ts)
  **ADMIN/SUPER ADMIN** - the new functionality described in the user story
  **USER** - requires the user to be the same user that's executing the command (like editing self activity status)
  **?** - thing like global GET requests (like cities for example) that doesn't require additional requests

EDITING LINK TO MAPPING GOOGLE SHEETS:
https://docs.google.com/spreadsheets/d/1Nfm__ZnuOR0o__2p0xAmoN9uWaE7JMHC2lj01AGgs1M/edit?usp=sharing

## Issue
the way I see it ( and I'm inviting everyone to express their own opinion about this) there are 2 main options here:
### 1. applying the function at the root
there are 2 ways of doing that -
#### applying different middlewares at each route's base
this works great for routes like **investigationInfo** where all of the endpoints are at a similar scope, but at other routes like **users** it almost requires a complete re-write of the route to get it to work properly.
#### modeling the API route to each middleware
basically applying to the base a root a middle-middleware that determines what middleware to use in what case, 
problem with that is that by looking at the routes I cant seem to find a way to categorize each middleware by any means other than hard modeling (with something like an Object that dictates each route and its appropriate middleware - that also requires new functions to be added to the model whenever they are created)
### 2. applying the middlewares at each endpoint
this is basically applying each function with the appropriate middleware based on the scope (described in the excel), which also requires every new endpoint that is added to be classified but with how the endpoints looks its appearing to be the mode effective solution

## I'm inviting everyone to comment on this issue and the sheet what they think is the best way to approach this and if there's any better way of doing this 😄 

**NOTE:** this is not referring to the middlewares themselves only to the best way to apply them.

**Comment by Noam6421** [comment]
I agree that the second solation is more effective in that case and I think it is the best approach.
